version: '3.5'

services:
    dev:
        image: "fauxneticien/qbe-std_feats_eval"
        volumes:
            # For development use, 
            # mount entire repo, including scripts
            - ${PWD}/:/home/qbe-std_feats_eval
        working_dir: /home/qbe-std_feats_eval
        # entrypoint:
        #    - /bin/bash
        command: sh -c 'python scripts/wav_to_w2v2-feats.py --dataset gos-kdl --stage transformer --layer 11 --model wav2vec2-dutch-large --queries_dir synthesized_queries && python scripts/feats_to_dtw.py wav2vec2-dutch-large_transformer-L11 gos-kdl --queries_file synthesized_queries.pickle'
        stdin_open: true
        tty: true

    prod:
        image: "fauxneticien/qbe-std_feats_eval"
        volumes:
            # For 'production' use,
            # mount only data directory
            - ${PWD}/data:/home/qbe-std_feats_eval/data
        working_dir: /home/qbe-std_feats_eval
        entrypoint:
            - /bin/bash
        stdin_open: true
        tty: true

    shennong:
        image: "fauxneticien/shennong"
        volumes:
            - ${PWD}/:/tmp
        working_dir: /tmp
        env_file:
            - .env
        #entrypoint:
        #    - /bin/bash
        command: sh -c 'eval "$$(conda shell.bash hook)" && conda activate shennong && python scripts/wav_to_shennong-feats.py ${FEATURE} gos-kdl --queries_dir synthesized_queries'
        stdin_open: true
        tty: true
